# Conexao com a base de dados (valores virão das variáveis de ambiente)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?ssl=true&sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.gmvptbiixyuptzurdhmk
spring.datasource.password=zEy4mhJO4SYO7uuN

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Properties (valores virão das variáveis de ambiente)
jwt.secret=k3+N5n7s/5sE2qL9vC1rX8yZ0wB4gH6jF3kU7lM9pA0=
jwt.expiration=86400000

# Garante que o servidor use a porta que o Render fornecer
server.port=${PORT:8080}
server.servlet.context-path=/eventHub