CREATE SCHEMA public;

-- 1. Criação dos ENUMS (Garante integridade dos dados e evita strings soltas)
CREATE TYPE public.role_type AS ENUM ('USER', 'ADMIN', 'ORGANIZER', 'STAFF');
CREATE TYPE public.ticket_status AS ENUM ('ATIVO', 'UTILIZADO', 'CANCELADO', 'PENDENTE');
CREATE TYPE public.discount_type AS ENUM ('PORCENTAGEM', 'FIXO');

-- 2. Tabela de USUÁRIOS (Conta de Acesso)
CREATE TABLE public.users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- Corrigido o problema de Sequence
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL, -- TEXT é mais seguro que VARCHAR para hash
    role public.role_type NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- 3. Tabela de EVENTOS
CREATE TABLE public.events (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    location VARCHAR(255),
    max_participants INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

-- 4. Tabela de PARTICIPANTES (Quem vai ao evento)
-- user_id é NULLABLE para permitir "Guest Checkout"
CREATE TABLE public.participants (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT, 
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_participants PRIMARY KEY (id),
    CONSTRAINT fk_participants_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- 5. Tabela de TIPOS DE INGRESSO (Preços e Lotes)
CREATE TABLE public.ticket_types (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL, -- Ex: "VIP", "Pista", "Lote 1"
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00, -- BigDecimal no Java
    quantity INTEGER NOT NULL, -- Estoque total deste tipo
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ticket_types PRIMARY KEY (id),
    CONSTRAINT fk_ticket_types_event FOREIGN KEY (event_id) REFERENCES public.events(id)
);

-- 6. Tabela de CUPONS DE DESCONTO
-- Adicionei event_id (Nullable) para permitir cupons específicos de evento
CREATE TABLE public.discount_coupons (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT, -- Se NULL, é cupom global. Se preenchido, só vale p/ esse evento.
    code VARCHAR(50) NOT NULL UNIQUE,
    discount_value NUMERIC(10, 2) NOT NULL,
    discount_type public.discount_type NOT NULL DEFAULT 'PERCENT',
    valid_until DATE,
    max_uses INTEGER DEFAULT 0, -- 0 = Ilimitado
    uses INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_discount_coupons PRIMARY KEY (id),
    CONSTRAINT fk_coupons_event FOREIGN KEY (event_id) REFERENCES public.events(id),
    CONSTRAINT chk_coupon_uses CHECK (max_uses = 0 OR uses <= max_uses)
);

-- 7. Tabela de TICKETS (O ingresso gerado)
CREATE TABLE public.tickets (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL,         -- Redundância útil para performance
    ticket_type_id BIGINT NOT NULL,   -- Liga ao preço/tipo
    participant_id BIGINT NOT NULL,   -- Liga ao dono do ingresso
    discount_coupon_id BIGINT,        -- Nullable (nem todo mundo usa cupom)
    ticket_code VARCHAR(100) NOT NULL UNIQUE, -- O hash para o QR Code
    status public.ticket_status NOT NULL DEFAULT 'ATIVO',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_tickets PRIMARY KEY (id),
    CONSTRAINT fk_tickets_event FOREIGN KEY (event_id) REFERENCES public.events(id),
    CONSTRAINT fk_tickets_type FOREIGN KEY (ticket_type_id) REFERENCES public.ticket_types(id),
    CONSTRAINT fk_tickets_participant FOREIGN KEY (participant_id) REFERENCES public.participants(id),
    CONSTRAINT fk_tickets_coupon FOREIGN KEY (discount_coupon_id) REFERENCES public.discount_coupons(id)
);

-- 8. ÍNDICES
CREATE INDEX idx_tickets_event ON public.tickets(event_id);
CREATE INDEX idx_tickets_participant ON public.tickets(participant_id);
CREATE INDEX idx_tickets_code ON public.tickets(ticket_code);
CREATE INDEX idx_ticket_types_event ON public.ticket_types(event_id);
CREATE INDEX idx_participants_email ON public.participants(email);
CREATE INDEX idx_users_email ON public.users(email);